baseURL = "http://example.org/"
languageCode = "en-us"
title = "Bauer Music Studio"
theme = "ananke"

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = -110

  [[menu.main]]
    name = "How I Teach"
    url = "/howIteach/"
    weight = -100

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = -110

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = -100