baseURL = "https://victorious-ocean-0a9a5f01e.azurestaticapps.net/"
languageCode = "en-us"
title = "Bauer Music Studio"
theme = "Smarty"
cleanDestinationDir = true

[params]
showtemplateinfo = "true"

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifer = "Method and Pricing"
    name = "Method and Pricing"
    url = "/methodandpricing/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 40