baseURL = "https://www.bauermusicstudio.com/"
languageCode = "en-us"
title = "Bauer Music Studio"
theme = "Smarty"
cleanDestinationDir = true
googleAnalytics = "G-TMY68L3RL0"
disableKinds=["taxonomy","term"]
[taxonomies]
  category="categories"
  tag="tags"

  
[params]
showtemplateinfo = "true"

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifer = "Method and Pricing"
    name = "Method and Pricing"
    url = "/methodandpricing/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 40