baseURL = "http://example.org/"
languageCode = "en-us"
title = "Bauer Music Studio"
theme = "Smarty"

[menu]

  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "How I Teach"
    url = "/howIteach/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 40