# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Smarty Theme for BauerMusicStudio"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://www.bauermusicstudio.com"
tags = ["website"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.64.0"

[author]
  name = "Grace"
  homepage = "https://www.bauermusicstudio.com/"
